# See https://grafana.com/docs/tempo/latest/configuration/

server:
  http_listen_port: 3200

distributor:
  # Receivers for otlp only (we omit zipkin and jaeger)
  receivers:
    otlp:
      protocols:
        grpc:
        http:
  log_received_spans:
    enabled: true

# TODO: Solution based on minio!
storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/blocks
