extensions:
  health_check:
#    port: 13133 # the default port

receivers:
  otlp:
    protocols:
      grpc:
      # http:

processors:
  batch:

exporters:
  otlp:
    endpoint: "localhost:5317"
#  prometheus:
#    endpoint: "prometheus-sb3:9090"
  logging:
    logLevel: debug

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      # exporters: [logging]
      exporters: [otlp]
    traces:
      receivers: [otlp]
      processors: [batch]
      # exporters: [logging]
      exporters: [otlp]

  # we want a health check
  extensions: [health_check]